### ISSUE TITLE
how to access argocd dashboard?

### ISSUE THREAD

**Issue by nguyentrungduc134** [nguyentrungduc134/signalfx_argocd#16]
To access the **ArgoCD dashboard**, follow these steps based on your setup. Here are the main approaches for accessing the ArgoCD UI:

### **Option 1: Using kubectl port-forward**

If you haven't set up an external load balancer for ArgoCD, you can use **`kubectl port-forward`** to expose the ArgoCD dashboard locally.

1. **Port Forward ArgoCD Server:**
   Use the following `kubectl` command to forward the ArgoCD server port to your local machine.

   ```bash
   kubectl port-forward -n argocd svc/argocd-server 8080:80
   ```

   This will forward port **80** of the **`argocd-server`** service to **port 8080** on your local machine.

2. **Access ArgoCD Dashboard:**
   Open your browser and go to `http://localhost:8080`. You should be able to access the **ArgoCD UI**.

3. **Login to ArgoCD:**
   - Default username: `admin`
   - Default password: You can get the default password from the Kubernetes secret:
     ```bash
     kubectl get secret argocd-initial-admin-secret -n argocd -o jsonpath='{.data.password}' | base64 -d
     ```

### **Option 2: Exposing ArgoCD via a Load Balancer (For Production Use)**

If you want ArgoCD to be accessible over the internet (or for production environments), you can expose it via an **Ingress** or **LoadBalancer** service.

#### **1. Modify ArgoCD Service to Use LoadBalancer:**

In your **ArgoCD Helm deployment**, you can modify the `argocd-server` service to use `LoadBalancer`. Here's how you can update your values:

```yaml
server:
  service:
    type: LoadBalancer
```

#### **2. Apply the Changes:**
```bash
kubectl apply -f values.yaml  # or `helm upgrade` if using Helm
```

#### **3. Get External IP:**
After a few minutes, check for the **external IP** of the **`argocd-server`** service:
```bash
kubectl get svc -n argocd
```

The **EXTERNAL-IP** column will show the external IP address where ArgoCD is now accessible.

#### **4. Access ArgoCD Dashboard:**
Now you can access ArgoCD by navigating to the **external IP** in your browser:
```
http://<external-ip>:80
```

#### **5. Login to ArgoCD:**
Use the default login credentials as mentioned earlier.

### **Option 3: Accessing ArgoCD with Ingress**

If you're using an **Ingress controller**, you can set up an **Ingress resource** to expose ArgoCD.

Here is an example of an **Ingress configuration**:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: argocd.example.com  # Set this to your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80
```

1. Apply the Ingress:
   ```bash
   kubectl apply -f argocd-ingress.yaml
   ```

2. Make sure that your domain (`argocd.example.com`) is pointed to the Ingress controller’s IP address.

3. Access ArgoCD by navigating to the **Ingress URL** in your browser:
   ```
   http://argocd.example.com
   ```

---

### **Summary of Access Methods:**

- **For local access**: Use `kubectl port-forward` to access the dashboard at `http://localhost:8080`.
- **For production**: Expose ArgoCD via a LoadBalancer or Ingress for external access.

Let me know if you need further help!
