### ISSUE TITLE
Basically I have different ArgoCD clusters. Like dev, prod, stage, test. I want to display ArgoCD sync as  signalfx events on a dashboard.

### ISSUE THREAD

**Issue by nguyentrungduc134** [nguyentrungduc134/signalfx_argocd#4]
You can achieve this by integrating ArgoCD notifications with SignalFx (Splunk Observability Cloud). Here’s a high-level approach:

### 1. **Enable ArgoCD Notifications**  
- If not already enabled, install and configure the ArgoCD notifications controller.
- Define triggers and subscriptions in `argocd-notifications-cm`.

### 2. **Send Events to SignalFx**  
- SignalFx supports ingesting events via HTTP. Use the webhook service in ArgoCD notifications:
  ```yaml
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: argocd-notifications-cm
  data:
    service.signalFx: |
      url: "https://ingest.<your-realm>.signalfx.com/v2/event"
      headers:
        X-SF-Token: <SIGNALFX_ACCESS_TOKEN>
      insecureSkipVerify: false
    trigger.on-sync: |
      - when: app.status.sync.status == 'Synced'
        send: [signalFx]
    template.signalFx: |
      message: "ArgoCD application {{.app.metadata.name}} is now in {{.app.status.sync.status}} state"
      webhook:
        signalFx:
          body: |
            {
              "category": ["ArgoCD"],
              "eventType": "sync_status",
              "dimensions": {
                "app": "{{.app.metadata.name}}",
                "project": "{{.app.spec.project}}",
                "status": "{{.app.status.sync.status}}",
                "cluster": "{{.context.argocdUrl}}"
              }
            }
  ```

### 3. **Deploy & Test**  
- Apply the config and test by triggering ArgoCD sync events.
- Verify events in SignalFx.

This approach allows real-time monitoring of sync events across clusters in a unified dashboard. Let me know if you need more details!
